### ISSUE TITLE
Rails 7 + Sidekiq Failed to execute Bundler::GemNotFound

### ISSUE THREAD

**Issue by kazmin** [zakird/wkhtmltopdf_binary_gem#132]
I'm runnig
Rails 7.0.2.3
Sidekiq 6.4.1
wkhtmltopdf-binary 0.12.6.5
wicked_pdf (2.1.0)

Pdfs are generated successfully on development both in sidekiq jobs and outside.

On production, pdfs are genearated properly in controllers. However in a sidekiq job, I get this error:

  Failed to execute:
["/home/deploy/project/shared/bundle/ruby/3.1.0/bin/wkhtmltopdf", "file:////tmp/wicked_pdf20220410-43652-85pwvm.html", "/tmp/wicked_pdf_generated_file20220410-43652-ceix3j.pdf"]

Error: PDF could not be generated!
 Command Error: /home/deploy/gomama_production/shared/bundle/ruby/3.1.0/gems/bundler-2.3.9/lib/bundler/definition.rb:481:in `materialize': Could not find rails-7.0.2.3, mysql2-0.5.3................(all the gems).........coffee-script-source-1.12.2, io-wait-0.2.1, crass-1.0.6 in any of the sources (Bundler::GemNotFound)
        from /home/deploy/gomama_production/shared/bundle/ruby/3.1.0/gems/bundler-2.3.9/lib/bundler/definition.rb:190:in `specs'

**Comment by kazmin** [comment]
The problem was with the sidekiq service. The .service file which runs the sidekiq service should have this as the exec start:

`ExecStart=/home/deploy/.rbenv/bin/rbenv exec bundle exec sidekiq -c 5 -e production`
